feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
mall:
  db:
    host: 192.168.80.100
    port: 3306
    database: hmall
    un: root
    pw: root
  swagger:
    package: czs.mall.user.controller
    title: 用户服务接口文档

